version: '4'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./ssl:/etc/apache2/ssl  # Asegúrate de agregar este volumen
    restart: always
